library(dplyr)
d = read.csv(file.choose())
attach(d)
c_dsl = filter(d,InternetService == "DSL")
View(c_dsl)
c_mnth = filter(d,Contract == "Month-to-month")
View(c_mnth)
s_m_c = filter(d,gender == "	Male" & PaymentMethod == "Electronic check" & SeniorCitizen == "1")
View(s_m_c)
c_tt = filter(d,tenure > 70 | TotalCharges > 8000)
View(c_tt)
c_2ms = filter(d,(Contract == "Two year" | PaymentMethod == "Mailed") & Churn == "Yes")
View(c_2ms)
