d = read.csv(file.choose())
View(d)
attach(d)
c_333 = sample_n(d,333)
c_1000 = sample_n(d,1000)
c_23 = sample_frac(d,0.23)
count(d,PaymentMethod)
count(d,Churn)
ftable(d$PaymentMethod)
table(PaymentMethod)
